name = input('Enter Your Name:')
branch = input('Enter Your Branch:') 
gender = input('Enter Your Gender:')
college = input('Enter Your College:')
age = int(input('Enter Your Age:'))
print("Name:",name)
print("Branch:",branch)
print("Gender:",gender)
print("College:",college)
print("Age:",age)